version: '3'
services:
  loonflow-redis:
    hostname: loonflow-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}

  loonflow-pg:
    hostname: loonflow-pg
    image: postgres:latest # change to 15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  loonflow-ui:
    hostname: loonflow-ui
    image: blackholll/loonflow-ui:latest
    platform: linux/amd64
    depends_on:
      - loonflow-redis
      - loonflow-pg
    ports:
      - 80:80

  loonflow-backend:
    hostname: loonflow-backend
    image: blackholll/loonflow-backend:latest
    platform: linux/amd64
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: loonflow-pg
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      REDIS_HOST: loonflow-redis
      REDIS_PASS: ${REDIS_PASSWORD}
    working_dir: /app/loonflow
    ports:
      - 8080:8080
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        gunicorn --bind 0.0.0.0:8000 --workers 4 --chdir /app/loonflow --pythonpath /app/loonflow loonflow.wsgi:application

  loonflow-task:
    hostname: loonflow-task
    image: blackholll/loonflow-backend:latest
    platform: linux/amd64
    depends_on:
      - loonflow-redis
      - loonflow-pg
      - loonflow-backend
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: loonflow-pg
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      REDIS_HOST: loonflow-redis
      REDIS_PASS: ${REDIS_PASSWORD}
    command:
      - sh
      - -c
      - |
        cd /app/loonflow
        celery -A tasks worker -l info -c 8 -Q loonflow

volumes:
  postgres_data:
