services:
  loonflow-redis:
    hostname: loonflow-redis
    image: redis:8.2.2
    container_name: loonflow-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}

  loonflow-pg:
    hostname: loonflow-pg
    image: postgres:15.14
    container_name: loonflow-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  loonflow-ui:
    hostname: loonflow-ui
    image: blackholll/loonflow-ui:r3.0.1
    container_name: loonflow-ui
    depends_on:
      - loonflow-redis
      - loonflow-pg
    ports:
      - 80:80

  loonflow-backend:
    hostname: loonflow-backend
    image: blackholll/loonflow-backend:r3.0.1
    container_name: loonflow-backend
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: loonflow-pg
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      REDIS_HOST: loonflow-redis
      REDIS_PASS: ${REDIS_PASSWORD}
      DJANGO_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
      TENANT_NAME: ${TENANT_NAME}
      TENANT_DOMAIN: ${TENANT_DOMAIN}

    working_dir: /app/loonflow
    ports:
      - 8000:8000
    command:
      - sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py createsuperuser --noinput --email ${ADMIN_EMAIL} --name ${ADMIN_NAME} || true
        gunicorn --bind 0.0.0.0:8000 --workers 4 --chdir /app/loonflow --pythonpath /app/loonflow \
        --access-logfile - --error-logfile - --log-level info \
        loonflow.wsgi:application

  loonflow-task:
    hostname: loonflow-task
    image: blackholll/loonflow-backend:r3.0.1
    container_name: loonflow-task
    depends_on:
      - loonflow-redis
      - loonflow-pg
      - loonflow-backend
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: loonflow-pg
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      REDIS_HOST: loonflow-redis
      REDIS_PASS: ${REDIS_PASSWORD}
    command:
      - sh
      - -c
      - |
        cd /app/loonflow
        celery -A tasks worker -l info -c 8 -Q loonflow

volumes:
  pg_data:
    name: ${PG_DATA_VOLUME}
