name: Build Web Image

on:
  push:
    tags:
      - 'r**'
    branches:
      - v3.0.1

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Depot for ARM building
        uses: depot/setup-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push multi-arch images
        run: |
          docker buildx build \
            --file docker_compose_deploy/loonflow-ui/Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --tag blackholll/loonflow-ui:${{ github.ref_name }} \
            --tag blackholll/loonflow-ui:test1 \
            --push .